@extends('layouts.app')

	@section('content')
		<modal></modal>
		@include('nav',array('type' => 3))
		<div class="container ">
			<div class="row">
				<h1 align="center">Términos y condiciones de Cabalachea </h1>		
				<strong>Titular de Cambalachea</strong>

				<br>
				<br>

				<i>Vivelab Bogotá y XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX<br>
				Avenida El Dorado Carrera 45 # 26 - 33<br>
				Bogotá,Colombia<br>
				info@cambalachea.co</i>

				<br>

				<h2>Glosario</h2>

				<p><strong>Cambalachea:</strong> Cambalachea.co es la plataforma que aloja de forma digital la dinámica de Banco de Tiempo. En adelante se denominará esta herramienta y al grupo de trabajo que está detrás del desarrollo e implementación de la misma  como “plataforma” y/o “Cambalachea”.<br> 
				<strong>Usuario:</strong> Dentro de Cambalachea el rol de usuario es aquella persona que se registra dentro de la plataforma e interactúa con ella a modo de exploración o de contacto con otro miembro.<br>
				<strong>Administrador:</strong> El rol de administrador es la o las personas encargadas de la curaduría y control de los relacionamientos dentro de la plataforma. Estos individuos no adquieren el rol de usuario.<br> 
				<strong>Titular:</strong> El titular de Cambalachea es la institución, persona jurídica o natural que tiene todos los derechos de Cambalachea.co. En este caso el Laboratorio de Innovación Vivelab Bogotá junto con la alta Consejeria de las TIC y la Alcaldía de Bogotá, adquieren el rol de propietario de la plataforma.<br>
				<strong>Habilidades:</strong> Destreza para desarrollar algunas tareas. En Cambalachea las terminologías como destrezas, fortalezas, servicios y aptitudes son tomadas como sinónimos por lo que dentro del documento se relacionarán sólo bajo este término.<br>
				<strong>Dorados:</strong> Dentro de Cambalachea el término “Dorados” hace alusión a la moneda digital que ésta maneja. Un Dorado equivale a una hora de tiempo, este se puede transar, donar o intercambiar. No tiene ni tendrá un valor económico.<br>
				<strong>SNS  (Social Network Services):</strong> Medio de comunicación social que permite establecer contacto con otras personas o plataformas por medio de la Web. Están conformadas por un conjunto de equipos, servidores, programas, conductores, transmisores, receptores y, sobre todo, por personas que comparten alguna relación  donde se mantienen intereses y actividades en común o se encuentran interesados en explorar los intereses y las actividades de otros usuarios.</p>

				<h2>Términos y condiciones de uso de Cambalachea</h2>
				<p>Todos los usuarios de los servicios prestados por Cambalachea, reconocen, conocen y aceptan los presentes términos y condiciones de acceso, uso, reporte, suministro, de información y datos, al momento de aceptar nuestras políticas,  restricciones, prohibiciones y condiciones en la etapa de registro a la plataforma, y por ende se obligan a dar cumplimiento sin excepción a lo establecido en los mismos, so pena de incurrir en algún delito tipificado en la normatividad vigente en Colombiana, sanción de tipo administrativo o disciplinario, restricción de acceso al sistema Cambalachea, entre otros.</p>

				<h2>Información acerca de Cambalachea</h2>

				<p>Cambalachea es una plataforma web  dedicada a estimular el intercambio entre los usuarios debidamente inscritos en la plataforma. Los usuarios deberán ofrecer sus competencias y servicios individuales a cambio de unidades de tiempo de otros miembros de la comunidad Cambalachea.<br>
				Los usuarios pueden usar las unidades de tiempo que se hallan en su propia cartera para generar intercambios con otros usuarios, por una cantidad de tiempo igual a la obtenida al proporcionar sus habilidades. Para obtener créditos de tiempo, los usuarios pueden ofrecer sus habilidades a otros usuarios o, alternativamente, realizar ciertas acciones (por ejemplo, invitar a otros amigos a inscribirse en el servicio, intercambiar con un nuevo miembro, etc.). La posibilidad de ejecutar estas acciones están específicamente descritas en la página de inicio y al registro de cada usuario.<br>
				Los intercambios de habilidades entre usuarios a través de la plataforma Cambalachea no acarreará ningún tipo de compensación  o remuneración económica.</p>

				<h2>Naturaleza de los servicios</h2>

				<p>Para fomentar el intercambio de habilidades dentro de la ciudad de Bogotá, Colombia; Cambalachea busca en sus usuarios una participación activa bajo los lineamientos de economía colaborativa en promoción y difusión del conocimiento individual a los miembros de la comunidad e incentivar el crecimiento social y personal con ayuda de la plataforma. Para ello, Cambalachea incorpora los “Dorados” para que los usuarios tengan una moneda virtual y así lograr adquirir nuevos servicios o promocionar sus habilidades. </p>

				<h3 id="l_indentado">1. Contenidos proporcionados por el usuario</h3>

				<p id="p_indentado">Los usuarios son responsables de sus propios contenidos y de los de terceros que compartan a través de Cambalachea, mediante la subida, publicación de contenidos en Cambalachea o por cualquier otro medio. Los usuarios eximen a Cambalachea de toda responsabilidad por reclamaciones o demandas que se puedan presentar contra el titular de la plataforma en relación con el uso indebido e ilícito de contenidos disponibles en la plataforma.<br>

				El titular no modifica los contenidos publicados por el usuario o por terceros, aunque en el evento de presentarse casos que presenten quejas de usuarios, contenidos que vayan en contravía de la finalidad y naturaleza de la plataforma o bien provenga una orden de autoridad pública en relación con contenidos que se consideren ofensivos o ilícitos, los administradores de la plataforma actuarán de forma inmediata, reportando los hechos a las autoridades, restringiendo el acceso, retirando la información, entre otras.</p>

				<h3 id="l_indentado2">1.1 Cuentas</h3>

				<p id="p_indentado2">Con el fin de utilizar ciertas funciones de la plataforma (por ejemplo, al adquirir los servicios), será necesario que el usuario cree una cuenta. Para crear una cuenta, debe proporcionar cierta información personal que se requiere para el proceso de registro a través de su cuenta de Facebook, google o LinkedIn. El usuario manifiesta y garantiza que:<br> 
				(i) toda la información necesaria que presente es verdadera y exacta; y<br> 
				(ii) mantendrá la exactitud de dicha información y se obliga a reportar cualquier modificación que haya sobre la misma. 
				El usuario es responsable de mantener la confidencialidad y seguridad de la información de inicio de sesión de cuenta (contraseñas, preguntas de validación, correos de confirmación, entre otros) y es completamente responsable de todas las actividades que ocurran durante el periodo en que se encuentre su cuenta activa.<br> 
				El usuario se obliga a notificar inmediatamente a Cambalachea, de cualquier uso no autorizado, o sospecha de uso no autorizado de su cuenta o cualquier otra violación de seguridad. Cambalachea, no puede y no será responsable por cualquier pérdida o daño causado por la falta de cumplimiento de los requisitos anteriores.<br> 
				El usuario se abstendrá de crear nuevas cuentas en el evento que se le haya eliminado previamente por la administración de la plataforma o prohibido cualquiera de los servicios. Por cualquier motivo Cambalachea, se reserva el derecho, a su discreción, de suspender o terminar su cuenta y negarle el uso presente o futuro del sitio o de los servicios (o cualquier parte del mismo) en cualquier momento y por cualquier razón. El usuario acepta que Cambalachea, no será responsable hacia él o cualquier tercero por cualquier suspensión o terminación de su cuenta o cualquier rechazo de cualquier uso de la plataforma. La información sobre su perfil incluirá información y contenido que el usuario proporcione, así como la información que recogemos de su cuenta con sitios de redes sociales ("Información de perfil"). Cambalachea, se reserva el derecho, a su sola discreción para eliminar la información del perfil en cualquier momento por cualquier razón. El usuario acepta que Cambalachea, no será responsable ante el usuario o cualquier tercero por dicha eliminación.</p>

				<h3 id="l_indentado2">1.2 Sitios de redes sociales.</h3> 
				<p id="p_indentado2">Los servicios pueden permitir a los usuarios conectarse con varias redes mediante SNS  (Social Network Services). Mediante la conexión de su cuenta SNS, el  usuario declara conceder el acceso a la información de su cuenta  SNS aceptando los términos y condiciones aquí descritos. Al conceder el acceso a Cambalachea, para la cuenta SNS, se entiende que podemos acceder, suministrar y almacenar cualquier información, contenido, u otros materiales que el usuario ha proporcionado o almacenado en su cuenta SNS ("SNS Contenido") accesible a través del sitio y los servicios de modo que está disponible en su cuenta. A menos que se especifique lo contrario en este acuerdo, todo el contenido del SNS se considerará su contenido de usuario (como se define más adelante) para todos los efectos del presente Acuerdo. LA RELACIÓN DE CADA USUARIO CON CADA SNS se rige únicamente por EL ACUERDO (S) CON TAL SNS, y Cambalachea renuncia a cualquier responsabilidad por la información personal e intransferible  que puede proporcionarse a los departamentos judiciales debido al SNS EN VIOLACIÓN de las configuraciones de privacidad que se haya definido en El SNS. Cambalachea, no hace ningún esfuerzo para revisar cualquier contenido SNS para cualquier propósito, incluyendo pero no limitado a la exactitud, legalidad o no infracción, y  así mismo no se hace responsable de cualquier Contenido del SNS.</p>

				<h3 id="l_indentado2">1.3 Moneda</h3>
				<p id="p_indentado2">La plataforma utiliza "Dorados" para facilitar las transacciones y animar a la gente a compartir sus servicios y habilidades. Los "Dorados" son de uso exclusivo de la plataforma y están disponibles únicamente en relación con SU USO DENTRO DEL SITIO Y DE LOS SERVICIOS. Los usuarios pueden ganar "Dorados" mediante el registro de una cuenta y hacer intercambio de ofertas. Posteriormente, los usuarios pueden utilizar los créditos que ganan para recibir servicios de otros usuarios. Cada nuevo miembro que se registre en Cambalachea, recibe "Dorados" al momento de la inscripción. Después de eso, los "Dorados" pueden ser recibidos de otros usuarios de Cambalachea, como parte de una transacción de servicios. Por último, de vez en cuando, Cambalachea, podrá conceder "Dorados" en el reconocimiento de buena conducta, y puede ofrecer ciertas formas adicionales de ganar "Dorados". Si el usuario no tiene suficientes "Dorados" dentro de Cambalachea para recibir un artículo o servicio que desea, se puede ofrecer al comercio una de sus habilidades a cambio. Mientras que sus "Dorados" no caduquen, ya que son personales durante el tiempo que se utiliza de forma activa dentro de su cuenta. Cambalachea tiene como límite individual de usuario el monto máximo de 12 "Dorados" donde el usuario podrá acomular más credito pero éste debe moverse de forma continua (3 semanas); es decir que si llegado el caso cualquier usuario superó o llegó a la moneda 13 y  estas monedas no fueron canjeadas a otro usuario Cambalachea dispondrá de ellas para promoción de campañas de índole social o premiación de usuarios activos. Cambalachea no se hace responsable de  la terminación de su cuenta por mal manejo y uso mal uso de la moneda interna, sus "Dorados" se cancelan automáticamente depuès de un año de inactividad. Su "Dorados" son específicos para el sitio y están disponibles únicamente en relación con su uso del sitio y los servicios. éstos no se pueden canjeados por dinero en efectivo o vendidos, transmitidos por herencia, o de otro modo asignados. Sólo se puede transferir sus "Dorados" a un usuario como parte de una transacción. Su "Dorados" pueden ser revocados o cancelados en cualquier momento y por cualquier motivo, incluyendo si su cuenta es cancelada o si el usuario no cumple con este Acuerdo. "Dorados" son los créditos promocionales que se emiten inicialmente de Cambalachea, y luego son transferidos entre los usuarios en relación con las transacciones y no para su consideración a Cambalachea, el usuario deberá indemnizar, defender y mantener indemne a Cambalachea, de cualquier reclamación de cualquier tipo que surjan en relación con el uso o la recepción de "Dorados".<br>
				La plataforma  incluye un componente de fichas virtuales ( "Dorados"), cada uno de los cuales constituye un permiso de licencia limitada para utilizar las funciones del sitio como se indica a continuación.<br>
				Cuando recibe "Dorados", Cambalachea, le otorga una licencia limitada ( "Licencia "Dorados"") para utilizar el "Dorados" como una muestra virtual que se llevó a cabo, permutado, negocian y / o transferido en el Sitio con otros usuarios (y / o "Dorados"), a cambio del permiso para acceder y utilizar contenido, aplicaciones, habilidades, y varios servicios de la lista de usuarios, de acuerdo con estas Condiciones de servicio. La Licencia "Dorados" es transferible por el titular a cualquier otro usuario, siempre que los usuarios cumplan con estas Condiciones de servicio y mantener sus cuentas al día. Con excepción de lo expresamente permitido por este Acuerdo o de otro modo expresamente permitido por Cambalachea, la Licencia de crédito no se puede otorgar una segunda licencia, gravado, transportado o someterse a cualquier derecho de supervivencia o disposición por efecto de la ley o de otra manera, y el usuario acepta que cualquier intento de violación de la disposición de estas Condiciones de servicio es nula y sin valor. Cambalachea, podrá revocar la licencia "Dorados" en cualquier momento sin previo aviso, reembolso o compensación en caso de que: (i) el programa "Dorados" es suspendido o terminado; (Ii) Cambalachea, determina que el titular de la cuenta ha cometido fraude conducta indebida o cualquier otra conducta ilegal; (Iii) Cambalachea, impone una fecha de caducidad en el uso de "Dorados" en cumplimiento de las leyes y reglamentos aplicables; (Iv) la cuenta del titular se termina por la violación de estas Condiciones de servicio; o (v) el titular deje de mantener una cuenta activa o termina este Acuerdo.<br>
				El usuario reconoce que no son "Dorados" real de la moneda o cualquier tipo de instrumento financiero y no se pueden canjear por cualquier suma de dinero de Cambalachea, en cualquier momento. Acuerda que Cambalachea, tiene el derecho de administrar, regular, controlar y / o modificar los derechos de licencia subyacentes tales "Dorados" como lo considere oportuno y que Cambalachea, no tendrá ninguna responsabilidad hacia el usuario basado en el ejercicio de este derecho. Cambalachea, no ofrece ninguna garantía en cuanto a la naturaleza, la calidad o el valor de las características del Sitio que serán accesibles a través del uso de "Dorados", o la disponibilidad o el suministro de "Dorados".<br>
				Cuando el usuario está de acuerdo a un perfil, su cantidad de la oferta en "Dorados" será restado de su cuenta "Dorados". Cuando otro usuario gana su perfil, se obtiene la cantidad de la oferta ganadora en Créditos añadido a su cuenta de crédito. Los créditos también se pueden comprar por un precio de sitio.</p> 

				<h3 id="l_indentado2">1.4 Cuentas inactivas</h3>

				<p id="p_indentado2">Una cuenta puede ser considerada "inactiva" cuando:</p>

				<p id="p_indentado3">&#9679; No termina el proceso de registro dentro de la plataforma.<br>
				&#9679; No existen servicios que se hayan enumerado u ofertas dentro de un período de 1 año.<br> 
				&#9679; Incurra en el incumplimiento o violaciòn de los presentes tèrminos y condiciones.<br>
				&#9679; Por solicitud directa del usuario.</p>
				<p id="p_indentado2">Las cuentas inactivas pueden ser cerradas y todos los créditos acumulados se perderán sin compensación alguna a favor del usuario; toda vez que es plena responsabilidad del usuario mantener constante actividad durante la activación de su cuenta en el marco de los presentes tèrminos y condiciones.</p>

				<h3 id="l_indentado">2. Sitio</h3> 
				<h3 id="l_indentado2">2.1 Licencia.</h3>
				<p id="p_indentado2">Sujeto a los términos de este Acuerdo, Cambalachea, le concede una licencia no transferible y no exclusiva para usar los aspectos de sitio y los servicios para su uso personal en el marco de la normatividad vigente en Colombia.</p> 
				<h3 id="l_indentado2">2.2 Ciertas Restricciones.</h3>
				<p id="p_indentado2">Los derechos concedidos al usuario en este Acuerdo están sujetos a las siguientes restricciones: (a) no debe licenciar, vender, alquilar, arrendar, transferir, asignar, distribuir, de acogida, o de otra forma explotar comercialmente el sitio o los servicios; (b) no debe modificar, crear trabajos derivados de, desensamblar, descompilar o realizar ingeniería inversa cualquier parte del Sitio o los servicios; (c) no debe acceder al sitio o servicios con el fin de construir un servicio similar o competitivo; y (d) A menos que contenga expresamente, ninguna parte del sitio o los servicios puede ser copiado, reproducido, distribuido, republicado, descargado, mostrado, publicado o transmitido en cualquier forma o por cualquier medio. Cualquier futura versión, actualización, u otra parte de la funcionalidad del sitio o servicios estarán sujetos a los términos de este acuerdo. Todos los derechos de autor y de propiedad intelectual sobre el contenido de cualquier sitio o servicios deben exhibirse en todas las copias del mismo. Cambalachea, no garantiza que el sitio o los servicios son apropiados para su uso en lugares distintos de la república de Colombia, más específicamente la ciudad de Bogotá.</p>
				<h3 id="l_indentado2">2.3 Modificación.</h3>
				<p id="p_indentado2">Cambalachea, se reserva el derecho, en cualquier momento y a su sola discreción, de modificar, suspender o interrumpir la plataforma o los servicios o cualquier parte del mismo, con o sin previo aviso y por cualquier motivo. El usuario acepta que Cambalachea, no será responsable ante el usuario o cualquier tercero por cualquier modificación, suspensión o interrupción del sitio o de los servicios o cualquier parte del mismo.</p>
				<h3 id="l_indentado2">2.4 Soporte y Mantenimiento; Actualizaciones.</h3>
				<p id="p_indentado2">El usuario reconoce y acepta que Cambalachea, no tendrá ninguna obligación de proporcionarle cualquier soporte o mantenimiento en relación con el Sitio o los servicios. El usuario acepta que Cambalachea, no está obligado a crear o proporcionar correcciones, actualizaciones, mejoras, correcciones de errores y / o mejoras del Sitio o los servicios (cada uno un "Actualizar"). Sin embargo, en el caso de Cambalachea, decide ofrecer una actualización, el usuario acepta que Cambalachea, podrá modificar el presente Acuerdo en relación con dicha actualización sin previo aviso específico para el usuario y que su uso del Sitio o los servicios después de dicha actualización está condicionada a la aceptación de cualquier acuerdo revisado. Al utilizar el Sitio o los servicios después de una actualización, el usuario representa que ha revisado la versión vigente del Acuerdo y acepta estar obligado por dicha versión. Todas las actualizaciones se rige por la versión de este Acuerdo publicado por Cambalachea, a partir de la fecha de utilizar el Sitio o los servicios después de dicha actualización.</p>

				<h3 id="l_indentado2">2.5 Propiedad.</h3>
				<p id="p_indentado2">Excluyendo su contenido de usuario (definido más adelante), el usuario reconoce y acepta que (i) el sitio y los servicios son y seguirán siendo propiedad exclusiva de Cambalachea, y está sujeto a la protección bajo las leyes de copyright de Colombia y extranjeras y (ii) todos los derechos de propiedad intelectual, incluidos los derechos de autor, patentes, marcas comerciales y secretos comerciales, en el sitio y los servicios son propiedad de Cambalachea, tanto como el nombre, logotipo  y todos los nombres de productos relacionados con el sitio o servicios pertenecientes y/o adquiridos con  "Dorados". No se concede ningún derecho o licencia para usarlos por implicación, impedimento o de otra manera. La provisión del sitio y los servicios no se transfieren al usuario o cualquier tercero ningún derecho, título o interés en o para dichos derechos de propiedad intelectual. Cambalachea, y sus proveedores se reservan todos los derechos no concedidos en este acuerdo.</p>
				<h3 id="l_indentado2">2.6 Evaluación.</h3>
				<p id="p_indentado2">El usuario acepta que la presentación de las ideas, sugerencias y / o propuestas a nosotros ( "Comentarios") es a su propio riesgo y que Cambalachea, no tiene obligaciones (incluyendo, sin limitación de obligaciones de confidencialidad) con respecto a dichos Comentarios. El usuario manifiesta y garantiza que tiene todos los derechos necesarios para presentar los comentarios.<br> 
				El usuario otorga a Cambalachea, perpetua, irrevocable, mundial, no exclusiva y totalmente sublicenciable la licencia para usar, reproducir, ejecutar, exhibir, distribuir, adaptar, modificar sin derechos de autor, volver a formatear , crear trabajos derivados, y de otra manera comercialmente o no comercialmente explotar de cualquier forma que considere oportuna, todas y cada uno de los permisos para sublicenciar los derechos anteriores.</p>


				<h3 id="l_indentado2">2.7 El uso del sitio.</h3> 
				<p id="p_indentado2">Al unirse a este sitio, el usuario se convierte en un miembro de la plataforma Cambalachea. Cada miembro de listas de habilidades / servicios que él o ella se experimenta con otros miembros de la comunidad. El momento de registro, puede recibir un cierto número de "Dorados" para hacer una oferta en el mercado (límite de un conjunto de "Dorados" libre por usuario). Para cada servicio que se realiza, el usuario podrá  ganar un cierto número de "Dorados" basándose en el resultado de la oferta. Con sus "Dorados", se puede hacer una oferta en los servicios en el mercado de otros miembros.<br>
				Cuando se acordó recibir "Dorados" por un servicio que el usuario enumeró, los "Dorados" de la otra parte se transfieren automáticamente a su cuenta o se mantiene en estado "pendiente" por Cambalachea, hasta se prestan los servicios.<br>
				El usuario acepta no publicar contenido o anuncios en una categoría inadecuada o áreas del sitio.<br>
				El usuario acepta no violar ninguna ley, derechos de terceros o nuestras políticas.<br>
				El usuario se compromete a prestar los servicios acordados de el usuario, a menos que el ganador no cumple con los términos de su perfil o si no puede autenticar la identidad de la otra parte.<br>
				El usuario se compromete a no manipular el precio en “Dorados” o interferir con ninguna de las ofertas de terceros.<br>
				El usuario acepta no publicar contenidos falsos, inexactos, difamatorio, calumnioso o (incluyendo información personal).<br>
				El usuario se compromete a no promover vínculos de referencia o dentro de Cambalachea usando SPAM o tácticas engañosas.<br>
				El usuario se compromete a no solicitar transacciones fuera de línea o canje de habilidades o servicios por dinero en efectivo.
				El usuario se compromete a no distribuir o publicar SPAM, no solicitado, o las comunicaciones electrónicas a granel, cadenas de cartas o esquemas piramidales.<br>
				El usuario acepta no recopilar información sobre los usuarios, incluyendo direcciones de correo electrónico, nombres, listados, etc. sin su consentimiento.<br>
				En la actualidad, la membresía de Cambalachea es libre, pero puede instituir un cargo en algún momento en el futuro para sufragar el coste de proporcionar este servicio valioso. Si se decide añadir tarifas, se le dará previo  aviso a los usuarios y se da la oportunidad de aceptar o rechazar los cargos.<br>
				El usuario entiende que, a excepción de la información, productos o servicios claramente identificados como proporcionados por Cambalachea, no opera, controla ni aprueba ninguna información, productos o servicios en Internet de ninguna manera. También se  entiende que Cambalachea, no puede y no garantiza que los archivos disponibles para descargar a través del sitio se encuentre libre de infección o virus, gusanos, caballos de Troya u otro código que manifieste propiedades contaminantes o destructivas. El usuario es responsable de implementar suficientes procedimientos y controles para satisfacer sus requisitos particulares para la exactitud de entrada y salida de datos, y para mantener un medio externo al sitio para la reconstrucción de cualquier dato perdido.</p>

				<h2>Contenidos proporcionados por los usuarios</h2>
				<p>Al enviar, publicar o mostrar contenidos en o a través de Cambalachea, el usuario concede al titular una AUTORIZACIÒN y licencia sin restricciones territoriales, no exclusiva, gratuita y con derecho a conceder sublicencias, para utilizar, copiar, reproducir, tratar, adaptar, modificar, publicar, transmitir, mostrar y distribuir dicho contenido en cualquier soporte o mediante métodos de distribución que se encuentren actualmente disponibles o que puedan ser desarrollados en el futuro, de conformidad con el manual de polìtica de tratamiento de datos personales del titular.<br>
				Así mismo el usuario como titular de sus datos personales autoriza dando la aceptaciòn a èstos tèrminos y condiciones al momento de culminar el registro en la plataforma, el uso de sus datos personales para los fines establecidos en la polìtica de tratamiento de datos personales.<br>
				Los usuarios se comprometen a compartir en Cambalachea únicamente los contenidos que sean de su exclusiva autorìa o que cuenten con autorizaciòn para utilizar, copiar, reproducir, tratar, adaptar, modificar, publicar, transmitir, mostrar y distribuir su contenido.  Estos contenidos deben ilustrar apropiadamente el tipo de servicio ofrecido y el proceso que se generó en el intercambio.</p>


				<h2>Exención de responsabilidad</h2>
				<p>El usuario exonera de toda responsabilidad a Cambalachea (incluyendo a sus filiales, participadas, sus representantes, administradores, agentes, licenciantes, socios y empleados, según corresponda) respecto de cualesquiera reclamaciones o demandas, incluyendo gastos de defensa jurídica, que pudieran derivarse de daños a otros usuarios o a terceros, en relación con los contenidos publicados online, infracciones legales o de las disposiciones de las presentes condiciones de uso.
				En particular, los usuarios se comprometen a indemnizar a Cambalachea respecto a cualquier acción o reclamación compensatoria, tasa, gravamen o penalización que se derive o esté relacionada con el trabajo hecho por los usuarios para otros usuarios o para terceros.<br>
				Además, el usuario asume total responsabilidad y riesgo por EL USO DEL SITIO Y DE INTERNET, Cambalachea. PROPORCIONA EL SITIO Y LA INFORMACIÓN RELACIONADA "COMO ES" Y NO alguna expresa o implícita, DECLARACIÓN DE APROBACIÓN DE TIPO (INCLUYENDO SIN LIMITACIÓN GARANTÍAS DE TÍTULO O NO, O LAS GARANTÍAS DE COMERCIALIZACIÓN O IDONEIDAD PARA UN FIN DETERMINADO ) CON RESPECTO AL SERVICIO, LA INFORMACIÓN DE BIENES O SERVICIO PROPORCIONADO A TRAVÉS DEL SERVICIO O DE INTERNET EN GENERAL, Y CAMBALACHEA. NO SERÁ RESPONSABLE DE CUALQUIER costo o daño derivado directa o indirectamente de cualquier transacción. Es solamente su responsabilidad evaluar la exactitud, integridad y utilidad de todas las opiniones, consejos, servicios, mercancías y demás información facilitada través del servicio o en Internet en general. Cambalachea, NO GARANTIZA QUE EL SERVICIO será ininterrumpido o libre de errores o que los defectos EN EL SERVICIO SERÁ CORREGIDO.<br>
				Además entiende que la naturaleza pura de Internet contiene materiales sin editar algunas de ellas sexualmente explícitos o pueden ser ofensivos para el usuario. SU ACCESO A tales materiales es bajo su propio riesgo.</p>

				<h2>Usos prohibidos</h2>
				<p>El Servicio sólo podrá usarse de conformidad con las presentes Condiciones.<br>
				Los usuarios se abstendrán de:</p>
				<p id="p_indentado3">&#9679; Realizar ingeniería inversa, descompilar, desensamblar, modificar o crear productos derivados basados en Cambalachea o cualquier parte de ésta;<br>
				&#9679; Eludir cualquier sistema informático utilizado por Cambalachea o sus licenciantes para proteger el contenido accesible a través de ésta;<br>
				&#9679; Copiar, almacenar, editar, modificar, preparar cualquier producto derivado o alterar de cualquier modo los contenidos proporcionados a través de Cambalachea;<br>
				&#9679; Utilizar cualquier robot, “spider”, aplicación de búsqueda/recuperación de sitios web u otro dispositivo, proceso o medio automático para acceder, recuperar, realizar “web scraping” o indexar cualquier parte de Cambalachea o de sus contenidos;<br>
				&#9679; Alquilar, otorgar licencias o sub-licencias Cambalachea;<br>
				&#9679; Injuriar, ofender, acosar, realizar prácticas amenazantes, amenazar o violar los derechos de terceros de cualquier otro modo;<br>
				&#9679; Difundir o publicar contenidos que sean ilegales, obscenos, ilegítimos, injuriantes o inapropiados;<br>
				&#9679; Compartir con o autorizar a terceros para que usen sus propias credenciales de acceso (identificación de usuario y contraseña) para acceder o compartir cualquier contenido en Cambalachea;<br>
				&#9679; Hacerse pasar por otra persona que no sean ellos mismos;<br>
				&#9679; Crear una cuenta para mandar spam o molestar a otros usuarios;<br>
				&#9679; Publicitar ofertas de ventas o vender cualquier bien o servicio en Cambalachea;<br>
				&#9679; Llevar a cabo o compartir cualquier tipo de encuestas, concursos, etc. en Cambalachea;<br>
				&#9679; Utilizar Cambalachea de cualquier forma inadecuada que viole las presentes Condiciones.<br>
				&#9679; Las demàs que puedan afectar el correcto uso de la plataforma y las que se determinen por el titular de la misma.</p>

				<h2>Derechos de propiedad intelectual</h2>
				<p>Todas las marcas registradas, sean nominativas o gráficas, y cualesquiera otras marcas, nombres comerciales, marcas de servicio, marcas mixtas, ilustraciones, imágenes o logotipos que aparezcan en relación con Cambalachea son y seguirán siendo propiedad exclusiva del titular o de sus licenciantes y están protegidas por las leyes en vigor en materia de marcas y tratados internacionales relacionados. Por consiguiente se encuentra expresamente prohibido el uso de las mismas sin previa y expresa autorización del titular de los derechos de propiedad sobre las mismas.</p>

				<h2>Edad mínima</h2>
				<p>Los usuarios declaran que son adultos según las leyes que les son aplicables. Bajo ninguna circunstancia podrán utilizar Cambalachea los menores de 18 años que según la Constitución Política de Colombia (Art. 98) es la edad prevista para el ejercicio de la ciudadanía.</p>

				<h2>Limitación de responsabilidad</h2>
				<p>Cambalachea, de conformidad con las disposiciones legales aplicables, será responsable contractual o extracontractualmente por los daños ocasionados a los usuarios o a terceros como consecuencia directa e inmediata de la actividad de Cambalachea, por dolo o culpa grave.<br>
				En la medida en que lo permitan las leyes aplicables, el usuario exonera expresamente al titular de Cambalachea de cualquier responsabilidad derivada de posibles daños o reclamaciones de cualquier tipo, incluyendo indemnizaciones por daños y perjuicios directos, indirectos, punitivos, incidentales, o especiales, o daños y perjuicios relativos a lucro cesante (pérdida de beneficios o de ingresos), pérdida de datos o costes de sustitución derivados del presente acuerdo o de cualquier otro modo relacionados con éste que sean de su culpa exclusiva.<br>
				El titular de Cambalachea no es parte en las relaciones entre usuarios y no ejerce control alguno sobre la calidad o las modalidades del servicio ofrecido por los usuarios para otros usuarios y, por tanto, no es responsable de la cantidad, calidad o grado de diligencia del servicio ofrecido por ellos. Además, el titular no efectúa ningún control sobre la fiabilidad de los comentarios y críticas relativos a miembros que ofrecen sus habilidades en Cambalachea, ni sobre la veracidad de los datos proporcionados por los usuarios en su propio perfil y, por tanto, no asume responsabilidad alguna respecto a esa información. Los administradores de Cambalachea sólo interfieren en resolución de conflictos entre los usuarios cuando estos lo requieren o alguna entidad legal lo solicite.</p> 

				<h2>Modificación de las presentes Condiciones</h2>
				<p>El titular se reserva el derecho de modificar estas Condiciones en cualquier momento, informando a los usuarios mediante su publicación en Cambalachea,
				Se entenderá que los usuarios que continúen utilizando Cambalachea tras la publicación de los cambios aceptan las nuevas Condiciones sin reservas.</p>

				<h2>Cesión del contrato</h2>
				<p>El titular de Cambalachea se reserva el derecho de transferir, ceder, realizar actos de disposición por novación o subcontratar todos o parte de los derechos y obligaciones derivados de las presentes condiciones, siempre y cuando los derechos del usuario previstos en estas Condiciones no se vean afectados. Dado el hecho de un cambio dentro de los Términos y condiciones por el cambio de titular de la plataforma se informará a todos los usuarios sobre este cambio con la potestad  de continuar con su cuenta activa.<br> 
				Los usuarios no podrán ceder ni transferir en modo alguno sus derechos u obligaciones adscritos a la cuenta del usuario.</p>

				<h2>Notificaciones</h2>
				<p>Todas las comunicaciones relativas a Cambalachea deberán ser enviadas utilizando los datos de contacto establecidos en este documento.</p>

				<br>
				<br>
			</div>		
		</div>
@endsection
